name: Metrics
on:
  schedule:
  - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
      with:
        committer_branch: main
        committer_message: "Update metrics"
        output_action: commit
        token: ${{ secrets.METRICS_TOKEN }}
